
export const ADD      = 'CONSTRUCTOR_ADD_INGREDIENT';
export const DELETE   = 'CONSTRUCTOR_DELETE_INGREDIENT';
export const RESET    = 'CONSTRUCTOR_RESET';
export const ORDER    = 'CONSTRUCTOR_CHANGE_ORDER';
